main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: '1.21.4'
author: Joseff Ribble
description: Automatically deletes chunks outside protected radius
commands:
  wildernessborder:
    description: Main command for WildernessBorder plugin
    usage: |
      /wildernessborder reload - Reload configuration
      /wildernessborder radius [blocks] - Get or set protected radius
      /wildernessborder regen - Force deletion of regions outside protected radius
permissions:
  wildernessborder.admin:
    description: Allows use of all WildernessBorder commands
    default: op